# Site settings
title: Eduardo Bustamante's website
description: "Eduardo Bustamante's (dualbus) personal website"
baseurl: ""
url: "https://dualbus.me"
twitter_username: dualbus
github_username: dualbus
encoding: utf-8
author: Eduardo Bustamante
copyright: 2014-2017

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
exclude: [makefile]
