# Site settings
title: dualbus' blog
description: "For great justice!"
baseurl: ""
url: "https://dualbus.me"
twitter_username: dualbus
github_username: dualbus

# Build settings
markdown: kramdown
permalink: pretty

encoding: utf-8
