# Site settings
title: Eduardo Bustamante's website
description: "Eduardo Bustamante's (dualbus) personal website. The topics discussed are: gnu/linux, free software (foss/floss), gnu bash, posix tools like sed, grep and awk, and similar."
baseurl: ""
url: "https://dualbus.me"
twitter_username: dualbus
github_username: dualbus
encoding: utf-8
author: Eduardo A. Bustamante López
email: dualbus+www@gmail.com
copyright: 2014-2019

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
exclude:
    - Dockerfile
    - Gemfile
    - Gemfile.lock
    - Makefile
