# Site settings
title: dualbus' blog
description: "For great justice!"
baseurl: ""
url: "https://dualbus.me"
twitter_username: dualbus
github_username: dualbus
encoding: utf-8

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
